config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  resources :menu_items
  resources :orders
  resources :users
  resources :order_items
  resources :menus
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  put "/order_items/:id" => "menu_items#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :menu_items
  validates :item, presence: true
  validates :rate, presence: true

  def self.all_menus
  end
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  belongs_to :menu

  def self.dinner
    all.where("category_name = 'Dinner'")
  end

  def self.breakfast
    all.where("category_name = 'Breakfast'")
  end

  def self.lunch
    all.where("category_name = 'lunch'")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user

  def self.of_user(user)
    all.where("user_id = ? and status = ?", user.id, "received")
  end

  def self.current_order(user)
    all.where("user_id = ? and status = ?", user.id, "not placed").last
  end

  def self.received_orders()
    all.where(status: "received", delivered_at: nil)
  end

  def self.delivered_orders()
    all.where(status: "delivered")
  end

  def self.delivered_orders(user)
    all.where(user_id: user.id, status: "delivered")
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :menu_item
  belongs_to :order
  validates :quantity, presence: true

  def self.current_order(order)
    where("order_id = ?", order.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  has_secure_password
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to sessions_path
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end

  def ensure_clerk_logged_in
    unless current_user.role == "clerk"
      redirect_to sessions_path
    end
  end

  def ensure_owner_logged_in
    unless current_user.role == "owner"
      redirect_to sessions_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    current_user
    render "index"
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :ensure_user_logged_in

  def index
    render "index"
  end

  def create
    name = params[:item]
    price = params[:rate]
    description = params[:description]
    category = params[:category]
    menu = params[:menu]

    new_item = MenuItem.new(name: name,
                            price: price,
                            description: description,
                            category_name: category,
                            menu_id: menu)
    if new_item.save
      flash[:notice] = "added a new menu item"
      redirect_to menu_items_path
    else
      flash[:error] = new_item.errors.full_messages.join(", ")
      redirect_to menus_path
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :ensure_owner_logged_in

  def index
    render "index"
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :ensure_user_logged_in

  def index
    if @current_user.role == "user"
      order = Order.current_order(current_user)
      @order = order
      @order_items = OrderItem.where("order_id = ?", order.id)
      render "index"
    else
      redirect_to users_path
    end
  end

  def update
    id = params[:id]
    item = MenuItem.find(id)
    order = Order.current_order(current_user)
    cart_item = OrderItem.new(
      menu_item_id: id,
      menu_item_name: item.name,
      menu_item_price: item.price,
      quantity: params[:quantity],
      order_id: order.id,
    )
    if !cart_item.save
      flash[:error] = cart_item.errors.full_messages.join(", ")
      redirect_to menu_items_path
    end
  end

  def destroy
    id = params[:id]
    order_item = OrderItem.find(id)
    order_item.destroy
    redirect_to order_items_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :ensure_user_logged_in

  def index
    if @current_user.role == "user"
      @orders = Order.of_user(current_user)
      @user_delivered = Order.delivered_orders(current_user)
      render "index"
    end
    if @current_user.role == "clerk" || @current_user.role == "owner"
      @orders = Order.received_orders
      @delivered = Order.delivered_orders
      render "index"
    end
    if @current_user == nil
      redirect_to users_path
    end
  end

  def create
    Order.create!(user_id: @current_user.id,
                  date: Date.today,
                  status: "not placed")
    redirect_to menu_items_path
  end

  def update
    if @current_user.role == "user"
      id = params[:id]
      order = Order.find(id)
      order.status = "received"
      order.save!
      redirect_to orders_path
    else
      id = params[:id]
      order = Order.find(id)
      order.status = "delivered"
      time = Time.now
      order.delivered_at = Time.now.to_formatted_s(:long)
      order.save!
      redirect_to orders_path
    end
  end

  def destroy
    id = params[:id]
    order = Order.of_user(current_user).find(id)
    order.destroy
    redirect_to menus_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      flash[:notice] = " you're signed in !"
      if user.role == "user"
        new_order = Order.create!(user_id: user.id,
                                  date: Date.today,
                                  status: "not placed")
      end
      redirect_to "/"
    else
      flash[:error] = "your login attempt was invalid. please try again"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render "users/new"
  end

  def create
    new_user = User.new(name: params[:name],
                        email: params[:email],
                        password: params[:password])
    if new_user.save
      flash[:notice] = " successfully registered"
      redirect_to sessions_path
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<body id="Main-body">

   

    <!-- <div class="container-below">
    <input type="text" placeholder="Start typing to search..." autocomplete="off">
    <button>Search</button>
      </div>--->
    <div class="container-below">

        <section class="below-text">
            <h1>EAT </h1>
        </section>

        <section class="below-text">
            <h1>DRINK </h1>
        </section>

        <section class="below-text">
            <h1>VISIT </h1>
        </section>

    </div>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container-top">
                                                                        
  <div class="nav-main">
    
    <%if @current_user %>

              <%if @current_user.role == "user"%>
               <%= link_to "My Orders", orders_path %>
               <%= link_to "sign-out" ,destroy_session_path, method:"delete"%>
                <%= link_to "Menus", menu_items_path %>
                <%= link_to "Home", "/" %>
              <%end%>
              <%if @current_user.role == "clerk"%>
               <%= link_to "All orders" ,orders_path%>
               <%= link_to "Home", "/" %>
               <%= link_to "sign-out" ,destroy_session_path, method:"delete"%>
               <%= link_to "Menus", menu_items_path %>
              <%end%>
              <%if @current_user.role == "owner"%>
                <%= link_to "All orders" ,orders_path%>
               <%= link_to "Home", "/" %>
               <%= link_to "sign-out" ,destroy_session_path, method:"delete"%>
               <%= link_to "Menus", menu_items_path %>
               <%= link_to "Add menu", menus_path %>

              <%end%>
      <%else%>
        <%= link_to "create account" ,users_path%>
        <%= link_to "login" ,sessions_path%>
        <%= link_to "Menus", menu_items_path %>
        <%= link_to "Home", "/" %>
        <%end%> 
       
            
           

            
   <span class="nav-head">
     <p>Beach view Restaurant </p>
   </span>
  </div>

    <%if flash[:error] %>
      <p style="color:darkred;margin-left:30%;"> 
        <%= flash[:error] %>
      </p>
    <%end%>

    <%if flash[:notice] %>
      <p style="color:green;margin-left:30%;"> 
        <%= flash[:notice] %>
      </p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/menu_items/_menus.html.erb
<main id="table-body">
<div class="MenuList">

<p><%=section_title%></p>
<table class="menu-table">
  <tr class="Table-header">
    
    <th class="heading"> Item</th>
    <th class="heading">Rate</th>
    <% if user_role == "user"%>
     <th class="heading">Cart</th>
    <%end%>
  </tr>
  <% menus.each do |item| %>
  <tr>
    <td class="table-data"><%=item.name%></td>
    <td class="table-data"><%=item.price%></td>
    <%if user_role == "user"%>
    <td class="table-data"><%= form_with(url: order_item_path(item.id), method: :put) do %>  
       <label for="quantity">Quantity:</label>
       <%= number_field_tag(name = 'quantity' ,nil,min: 1,class: 'quantity_field')%> 
       <%= button_tag 'Add to cart',type:'submit'%>
    <% end %></td>
    <%end%>
  </tr>
  <% end %>
</table>
</div>
</main>

app/views/menu_items/index.html.erb
<body id="Menu-body">
  
   <div class="below1">
     <div class="below1-right">
   </div>
   </div>
  <h1>Menu</h1>
<%= render partial: "menus", locals:{
                
         menus:MenuItem.breakfast,
         section_title: "Breakfast", 
         user_role: @current_user.role
            } %>

<%= render partial: "menus", locals:{
                
         menus:MenuItem.lunch,
         section_title: "Lunch",
           user_role: @current_user.role
        
            } %>

<%= render partial: "menus", locals:{
                
         menus:MenuItem.dinner,
         section_title: "Dinner",
         user_role: @current_user.role 
        
            } %>
 <%if @current_user.role == "user"%>
  <div class="box">
	<a class="button" href="/order_items">view cart</a>
  </div>
 <%end%>

</body>

app/views/menus/_add_menu.html.erb
 
     <p><%=section_title%>
    <%=form_with url:menu_items_path ,method: :post do |form|%>
        <div class="add-item">
         <p class="item-label">item : </p>
          <%= form.text_field :item ,class:"item-input"%>
         <div>
         <div class="add-section">
         <p class="item-label">rate : </p>
         <%= form.text_field :rate, class:"item-input"%>
       </div>
      <div class="add-section">
      <p class="item-label">description : </p>
      <%= form.select'description', raw("<option>south indian</option><option>north indian</option><option>chineese</option><option>tandoori</option>"), class:"item-input"%>
      </div>
       <div class="add-section">
      <p class="item-label">category : </p>
      <%= form.select 'category', raw("<option>Breakfast</option><option>lunch</option><option>Dinner</option><optionCold Drinks</option>"), class:"item-input"%>
      </div>
       <div class="add-section">
      <p class="item-label">menu : </p>
      <%= form.select 'menu', options_for_select(menu.collect{ |u| [u.name, u.id] }) , class:"item-input"%>
      </div>
      <div class="add-section">
       <%=form.submit "add", class:"item-submit" %>
      </div>
   <%end%>

app/views/menus/index.html.erb
<div class="below1">
     <div class="below1-right">
     </div>
     </div>


<h3> make a new menu or a add a item to a menu <h3>





<%= render partial: "add_menu", locals:{
                
        
         section_title: "add menu_item", 
         user_role: @current_user.role,
         menu: Menu.all,
         menu_item: MenuItem.all
            } %>

app/views/order_items/_order_cart.html.erb
<hr>
<section>
 <div>

    <% order_items.each do |item|%>
     <p>item:       <%= item.menu_item_name %>  </p>
     <p>price:       <%= item.menu_item_price%>   </p>
     <p>quantity:   <%= item.quantity %>         </p>
     <p> sum = <%= (item.menu_item_price * item.quantity) %> </p>
     <p>
       <%= form_with(url: order_item_path(item.id), method: :delete) do %>  
          <%= button_tag 'remove',type:'submit'%>
      <%end%>
    </p> 
    <%end%>
    
    <p> order cost =   <% sum = 0%>
                   <% order_items.each do |item|%> 
                 <% sum = sum + (item.menu_item_price * item.quantity) %>
                      <%end%>
                        <%= sum %>
    </p>
    <p><% if sum !=0%>
       <%= form_with(url: order_path(order.id), method: :put) do %>  
       <%= button_tag 'place order',type:'submit'%>
       <% end %>
       <p>
       <%= link_to "add more", menu_items_path %>
       </p>  
       <%else%>
        <h3> why don't you try out some from our menu ? </h3>
        <p>
        <%=link_to "menus", menu_items_path%>
        <p>
        <%end%>
    </p>
    

    
  </div>
  </section>

app/views/order_items/index.html.erb
<h1> here is your order </h1>

<%= render partial: "order_cart",locals:{
    
    order_items: @order_items,
    order: @order
}%>

app/views/orders/_user-cart.html.erb
  <hr>
  
    <%if cart !=nil %>
     <% if user_role == "owner"%>
      <h4>pending orders </h4>
     <%else%>
      <h4>pending orders </h4>
      <%end%>

     <% cart.each do |order|%>
       <li> 
       order id: <%=order.id%>
       ordered on: <%=order.date%> 
       order status: <%=order.status%>
       <br>
       <% if user_role == "clerk" %>
       <% user_id = order.user_id %>
       <% user = User.find(user_id)%>
       ordered by: <%=user.name %>  
           <%= form_with(url: order_path(order.id), method: :put) do %>  
            <%= button_tag 'delivered',type:'submit'%>
           <% end %>
        <%end%>
       </li>
       <%end%>
        <% last_order = Order.current_order(@current_user)%>
        <%if user_role == "user" && last_order.status == "received"%>
        <%= form_with(url: orders_path, method: :post) do %>  
            <%= button_tag 'make a another order',type:'submit'%>
        <% end %>
      <%end%>
      <%if user_role == "clerk" || user_role =="owner" %>
        <%if delivered%>
         <hr>
         <h4>delivered orders </h4>
         <% delivered.each do |order|%>
         <li>
          order id: <%=order.id%>
          ordered on: <%=order.date%> 
          delivered at: <%=order.delivered_at%>
          order status: <%=order.status%>
          <%user_id = order.user_id %>
          <% user = User.find(user_id)%>
           ordered by: <%=user.name %>  
         </li>
         <%end%>
        <%end%>
      <%end%> 
      <%if user_role == "user" && user_delivered%>
        <hr>
        <h4> delivered orders </h4>
        <% user_delivered.each do |order|%>
         <li>
          order id: <%=order.id%>
          ordered on: <%=order.date%> 
          delivered at: <%=order.delivered_at%>
          order status: <%=order.status%>
        <%end%>
      <%end%>
    <%else%>
      <h3> place an order with just few clicks !! </h3>
      <%=link_to "menus", menu_items_path%>
     <%end%>

   

app/views/orders/index.html.erb
<h1>  orders </h1>

<%= render partial: "user-cart",locals:{
    cart: @orders,
    user_role: @current_user.role,
    delivered: @delivered,
    user_delivered: @user_delivered
}%>

app/views/users/new.html.erb
<main id="user-body">
<h1 class="User-title"> sign up page </h1>

  <section class="User-Section">
   <%=form_with url:users_path do |form|%>
     <div class="Form-Section">
      <p class="Form-Label">Name : </p>
      <%= form.text_field :name ,class:"Form-Input"%>
     <div>
     <div class="Form-Section">
      <p class="Form-Label">Email : </p>
      <%= form.email_field :email, class:"Form-Input"%>
     </div>
     <div class="Form-Section">
      <p class="Form-Label">Password : </p>
      <%= form.password_field :password, class:"Form-Input"%>
      </div>
      <div class="Form-Section">
       <%= form.submit "Sign-Up", class:"Form-submit" %>
      </div>
    <%end%>
  </section>
</main>